---
- name: Run powershell script
  hosts: win
  gather_facts: false
  vars:
    ansible_user: Admin1
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_password: o-MBm;&m;0!.7F%
  tasks:
    - name: Run powershell script
      script: files/psscript.ps1

